version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: avance
      POSTGRES_PASSWORD: "osr18kdCDjwE10eSxitQR96MTnBXEoTC"
    volumes:
      - avance_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "ZDRxgTqr3UoulMgsmaBzvonWZjHZtgsV"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  avance_data:
